package main

import (
	"encoding/base64"
	"strings"
	"testing"
	"time"
)

// Generated by the server's own stack, so a divergence on either side breaks
// this test rather than breaking fallback in production:
//
//	key = hmac.new(b"test-jwt-secret-key", b"gateway-auth-cache",
//	               hashlib.sha256).hexdigest()
//	jwt.encode({"data": {...}, "exp": 1893456000}, key, algorithm="HS256")
//
// The key is used as the literal characters of that hex digest. PyJWT encodes a
// str key as UTF-8, so decoding the hex here would silently reject everything.
const (
	vectorMarkerKey   = "c39da1d83cc7b6640483842edfc77bfc0d6c6f84e9cda9fda44a3fd3b6b6d533"
	vectorMarkerToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiYWs6MzE5MjI1M2MxZjRhOWI3ZSIsImNvbnN1bWVyIjoiMzE5MjI1M2MxZjRhOWI3ZS5ncHVzdGFjay03IiwibW9kZWwiOiJteS1vcmcvcXdlbjMtOGIiLCJyb3V0ZSI6Im5zL2FpLXJvdXRlLXJvdXRlLTQyLmludGVybmFsIn0sImV4cCI6MTg5MzQ1NjAwMH0.BWBnPtKF2NbQuG8Cf9wZy6o_ZCw_9wcAvkygBgdyzMk"
	vectorMarkerExp   = 1893456000
	// The route the vector was minted on, and the one the redirect pass runs
	// under. A marker is only honoured when those differ -- see
	// resolveFromMarker -- so tests that expect one to verify must say they are
	// on the fallback pass.
	vectorMarkerRoute   = "ns/ai-route-route-42.internal"
	vectorFallbackRoute = "ns/ai-route-route-42.fallback.internal"
)

var vectorMarkerClaims = markerClaims{
	ID:       "ak:3192253c1f4a9b7e",
	Consumer: "3192253c1f4a9b7e.gpustack-7",
	Model:    "my-org/qwen3-8b",
	Route:    vectorMarkerRoute,
}

func markerNow() time.Time { return time.Unix(vectorMarkerExp-60, 0) }

func TestVerifyMarkerAcceptsPyJWTVector(t *testing.T) {
	claims, ok := verifyMarker([]byte(vectorMarkerKey), vectorMarkerToken, markerNow())
	if !ok {
		t.Fatal("a marker minted by the server's stack did not verify")
	}
	if claims != vectorMarkerClaims {
		t.Errorf("claims = %+v, want %+v", claims, vectorMarkerClaims)
	}
}

// Stronger than round-tripping: the bytes this plugin emits must be the bytes
// PyJWT emits, so either side can mint a marker the other reads.
func TestSignMarkerMatchesPyJWTByteForByte(t *testing.T) {
	got, err := signMarker([]byte(vectorMarkerKey), vectorMarkerClaims, time.Unix(vectorMarkerExp, 0))
	if err != nil {
		t.Fatalf("signMarker: %v", err)
	}
	if got != vectorMarkerToken {
		t.Errorf("signed marker diverged from PyJWT's encoding.\n got %s\nwant %s", got, vectorMarkerToken)
	}
}

func TestSignMarkerRoundTrip(t *testing.T) {
	now := time.Unix(1_790_000_000, 0)
	claims := markerClaims{ID: "ref:58", Consumer: "none", Model: "my-org/qwen3-8b", Route: vectorMarkerRoute}

	token, err := signMarker([]byte(vectorMarkerKey), claims, now.Add(markerTTL))
	if err != nil {
		t.Fatalf("signMarker: %v", err)
	}
	got, ok := verifyMarker([]byte(vectorMarkerKey), token, now)
	if !ok || got != claims {
		t.Fatalf("round trip failed: ok=%v claims=%+v", ok, got)
	}
	// One second past expiry the marker is dead, so it cannot be hoarded and
	// replayed as a general bearer token.
	if _, ok := verifyMarker([]byte(vectorMarkerKey), token, now.Add(markerTTL)); ok {
		t.Error("a marker verified at its own expiry instant")
	}
}

func TestVerifyMarkerRejects(t *testing.T) {
	valid := vectorMarkerToken
	parts := strings.Split(valid, ".")

	// `alg: none` with an empty signature -- the classic forgery, and here it
	// would hand over the one credential that bypasses tier 1 on a fallback.
	algNone := base64.RawURLEncoding.EncodeToString([]byte(`{"alg":"none","typ":"JWT"}`)) +
		"." + parts[1] + "."

	cases := []struct {
		name  string
		key   string
		token string
		now   time.Time
	}{
		{name: "wrong key", key: strings.Repeat("0", 64), token: valid, now: markerNow()},
		{
			name: "hex-decoded key", key: "",
			token: valid, now: markerNow(),
		},
		{name: "expired", key: vectorMarkerKey, token: valid, now: time.Unix(vectorMarkerExp, 0)},
		{name: "alg none", key: vectorMarkerKey, token: algNone, now: markerNow()},
		{
			name: "tampered payload", key: vectorMarkerKey, now: markerNow(),
			token: parts[0] + "." + base64.RawURLEncoding.EncodeToString(
				[]byte(`{"data":{"id":"ak:ffffffffffffffff","consumer":"x","model":"my-org/qwen3-8b"},"exp":1893456000}`),
			) + "." + parts[2],
		},
		{
			name: "truncated signature", key: vectorMarkerKey, now: markerNow(),
			token: parts[0] + "." + parts[1] + "." + parts[2][:len(parts[2])-4],
		},
		{name: "no dots", key: vectorMarkerKey, token: "not-a-jwt", now: markerNow()},
		{name: "empty", key: vectorMarkerKey, token: "", now: markerNow()},
		{
			name: "signature is not base64url", key: vectorMarkerKey, now: markerNow(),
			token: parts[0] + "." + parts[1] + ".!!!!",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			key := []byte(tc.key)
			if tc.name == "hex-decoded key" {
				// What a plugin that decoded the hex would be holding.
				key = mustHexDecode(t, vectorMarkerKey)
			}
			if _, ok := verifyMarker(key, tc.token, tc.now); ok {
				t.Error("marker verified but should have been rejected")
			}
		})
	}
}

// A payload with no exp must not read as "never expires" -- that would be an
// unbounded bearer credential.
func TestVerifyMarkerRejectsMissingExp(t *testing.T) {
	payload := base64.RawURLEncoding.EncodeToString(
		[]byte(`{"data":{"id":"ak:x","consumer":"c","model":"m"}}`))
	signingInput := jwtHeaderB64 + "." + payload
	token := signingInput + "." + base64.RawURLEncoding.EncodeToString(
		markerSignature([]byte(vectorMarkerKey), signingInput))

	if _, ok := verifyMarker([]byte(vectorMarkerKey), token, markerNow()); ok {
		t.Error("a correctly signed marker with no exp was accepted")
	}
}

func TestSplitNormalizedID(t *testing.T) {
	cases := []struct {
		id            string
		wantAccessKey string
		wantRef       string
		wantOK        bool
	}{
		{id: "ak:3192253c1f4a9b7e", wantAccessKey: "3192253c1f4a9b7e", wantOK: true},
		{id: "ref:58", wantRef: "58", wantOK: true},
		{id: "", wantOK: false},
		{id: "ak:", wantOK: false},
		{id: "ref:", wantOK: false},
		{id: "3192253c1f4a9b7e", wantOK: false},
		{id: "user:7", wantOK: false},
	}
	for _, tc := range cases {
		t.Run(tc.id, func(t *testing.T) {
			accessKey, ref, ok := splitNormalizedID(tc.id)
			if ok != tc.wantOK || accessKey != tc.wantAccessKey || ref != tc.wantRef {
				t.Errorf("got (%q, %q, %v), want (%q, %q, %v)",
					accessKey, ref, ok, tc.wantAccessKey, tc.wantRef, tc.wantOK)
			}
		})
	}
}

// The marker's identity must also be live in the key table, so the fixture
// carries the entry the vector's `id` claim names.
func markerTestConfig() PluginConfig {
	return PluginConfig{
		LocalAuth: LocalAuth{
			Enabled: true,
			Keys:    map[string]keyEntry{"3192253c1f4a9b7e": {Digest: vectorDigest, UserID: 7}},
		},
		AuthCache: AuthCache{Header: "x-gpustack-auth-cache", SigningKey: []byte(vectorMarkerKey)},
	}
}

func TestResolveFromMarker(t *testing.T) {
	headers := func(marker, model string) [][2]string {
		return [][2]string{
			{"x-gpustack-auth-cache", marker},
			{"x-higress-llm-model", model},
			// ai-proxy has replaced the client key by the fallback pass; the
			// marker must resolve regardless of what sits here.
			{"authorization", "Bearer gpustack_sysaksysaksysak_" + vectorSecret},
		}
	}

	t.Run("resolves on the fallback pass", func(t *testing.T) {
		id := resolveIdentity(markerTestConfig(), headers(vectorMarkerToken, "my-org/qwen3-8b"), vectorFallbackRoute, markerNow())
		if id.State != identityResolved {
			t.Fatalf("state = %v, want resolved", id.State)
		}
		if id.AccessKey != "3192253c1f4a9b7e" || id.Consumer != vectorMarkerClaims.Consumer {
			t.Errorf("id = %+v", id)
		}
	})

	t.Run("model binding is enforced", func(t *testing.T) {
		id := resolveIdentity(markerTestConfig(), headers(vectorMarkerToken, "my-org/other-model"), vectorFallbackRoute, markerNow())
		if id.State != identityUnresolved {
			t.Error("a marker was honoured for a model it was not issued for")
		}
	})

	t.Run("no signing key means markers are untouched", func(t *testing.T) {
		config := markerTestConfig()
		config.AuthCache.SigningKey = nil
		id := resolveIdentity(config, headers(vectorMarkerToken, "my-org/qwen3-8b"), vectorFallbackRoute, markerNow())
		if id.State != identityUnresolved {
			t.Error("a marker was trusted without a key configured")
		}
	})

	t.Run("kill switch disables tier 0 as well", func(t *testing.T) {
		config := markerTestConfig()
		config.LocalAuth.Enabled = false
		id := resolveIdentity(config, headers(vectorMarkerToken, "my-org/qwen3-8b"), vectorFallbackRoute, markerNow())
		if id.State != identityUnresolved {
			t.Error("local_auth off must stop the plugin touching markers at all")
		}
	})

	t.Run("a server-minted marker carries no id", func(t *testing.T) {
		serverStyle, err := signMarker([]byte(vectorMarkerKey),
			markerClaims{Consumer: "3192253c1f4a9b7e.gpustack-7", Model: "my-org/qwen3-8b",
				Route: vectorMarkerRoute},
			time.Unix(vectorMarkerExp, 0))
		if err != nil {
			t.Fatalf("signMarker: %v", err)
		}
		id := resolveIdentity(markerTestConfig(), headers(serverStyle, "my-org/qwen3-8b"), vectorFallbackRoute, markerNow())
		if id.State != identityUnresolved {
			t.Error("a consumer with no identity must fall through to be forwarded, not be asserted")
		}
	})
}

func TestMarkerClaimsFor(t *testing.T) {
	resolved := identity{State: identityResolved, AccessKey: "3192253c1f4a9b7e"}

	t.Run("mints for a resolved identity", func(t *testing.T) {
		claims, ok := markerClaimsFor(markerTestConfig(), resolved, "my-org/qwen3-8b", "3192253c1f4a9b7e.gpustack-7", vectorMarkerRoute)
		if !ok || claims != vectorMarkerClaims {
			t.Errorf("ok=%v claims=%+v, want %+v", ok, claims, vectorMarkerClaims)
		}
	})

	t.Run("mints for a ref identity", func(t *testing.T) {
		claims, ok := markerClaimsFor(markerTestConfig(),
			identity{State: identityResolved, Ref: "58"}, "m", "c", vectorMarkerRoute)
		if !ok || claims.ID != "ref:58" {
			t.Errorf("ok=%v claims=%+v", ok, claims)
		}
	})

	// Replacing the server's marker with an identity-less one would break the
	// very pass the marker exists for, so these must all decline.
	t.Run("declines when anything is missing", func(t *testing.T) {
		cases := []struct {
			name     string
			config   PluginConfig
			id       identity
			model    string
			consumer string
		}{
			{name: "unresolved identity", config: markerTestConfig(), id: identity{}, model: "m", consumer: "c"},
			{name: "no model", config: markerTestConfig(), id: resolved, consumer: "c"},
			{name: "no consumer", config: markerTestConfig(), id: resolved, model: "m"},
			{
				name: "no signing key", id: resolved, model: "m", consumer: "c",
				config: PluginConfig{LocalAuth: LocalAuth{Enabled: true}, AuthCache: AuthCache{Header: "x"}},
			},
			{
				name: "local auth off", id: resolved, model: "m", consumer: "c",
				config: PluginConfig{AuthCache: AuthCache{Header: "x", SigningKey: []byte(vectorMarkerKey)}},
			},
		}
		for _, tc := range cases {
			if _, ok := markerClaimsFor(tc.config, tc.id, tc.model, tc.consumer, vectorMarkerRoute); ok {
				t.Errorf("%s: minted a marker that should have been declined", tc.name)
			}
		}
	})
}

func mustHexDecode(t *testing.T, s string) []byte {
	t.Helper()
	out := make([]byte, len(s)/2)
	for i := range out {
		var b byte
		for j := range 2 {
			c := s[i*2+j]
			switch {
			case c >= '0' && c <= '9':
				b = b<<4 | (c - '0')
			case c >= 'a' && c <= 'f':
				b = b<<4 | (c - 'a' + 10)
			default:
				t.Fatalf("bad hex %q", s)
			}
		}
		out[i] = b
	}
	return out
}

// Revocation has no cache-invalidation step of its own: dropping the key from
// `keys` must be enough, even for a marker that is still cryptographically
// valid. Without this, a revoked key would keep working until its last marker
// expired -- and on a public route nothing else would catch it.
func TestMarkerStopsResolvingOnceRevoked(t *testing.T) {
	config := markerTestConfig()
	headers := [][2]string{
		{"x-gpustack-auth-cache", vectorMarkerToken},
		{"x-higress-llm-model", "my-org/qwen3-8b"},
	}
	if id := resolveIdentity(config, headers, vectorFallbackRoute, markerNow()); id.State != identityResolved {
		t.Fatalf("precondition: a live key must resolve, got %v", id.State)
	}

	config.LocalAuth.Keys = map[string]keyEntry{}
	if id := resolveIdentity(config, headers, vectorFallbackRoute, markerNow()); id.State != identityUnresolved {
		t.Error("a marker outlived its key: revocation must take effect on the next request")
	}
}

func TestMarkerStopsResolvingOnceExpired(t *testing.T) {
	config := markerTestConfig()
	past := markerNow().Unix() - 1
	config.LocalAuth.Keys = map[string]keyEntry{
		"3192253c1f4a9b7e": {Digest: vectorDigest, UserID: 7, Exp: &past},
	}

	id := resolveIdentity(config, [][2]string{
		{"x-gpustack-auth-cache", vectorMarkerToken},
		{"x-higress-llm-model", "my-org/qwen3-8b"},
	}, vectorFallbackRoute, markerNow())
	if id.State != identityUnresolved {
		t.Error("an expired key must not be revived by a marker signed while it was live")
	}
}

// A ref identity is checked against refs, which is the table's whole purpose:
// it cannot verify a credential, only confirm one has not been withdrawn.
func TestMarkerRefIdentityChecksRefsTable(t *testing.T) {
	config := markerTestConfig()
	token, err := signMarker([]byte(vectorMarkerKey),
		markerClaims{ID: "ref:58", Consumer: "c.gpustack-9", Model: "my-org/qwen3-8b",
			Route: vectorMarkerRoute},
		time.Unix(vectorMarkerExp, 0))
	if err != nil {
		t.Fatalf("signMarker: %v", err)
	}
	headers := [][2]string{
		{"x-gpustack-auth-cache", token},
		{"x-higress-llm-model", "my-org/qwen3-8b"},
	}

	if id := resolveIdentity(config, headers, vectorFallbackRoute, markerNow()); id.State != identityUnresolved {
		t.Error("a ref absent from refs must not resolve")
	}

	config.LocalAuth.Refs = map[string]refEntry{"58": {}}
	id := resolveIdentity(config, headers, vectorFallbackRoute, markerNow())
	if id.State != identityResolved || id.Ref != "58" {
		t.Errorf("a ref listed in refs must resolve, got %+v", id)
	}
}

// Which tier named the caller is the first thing worth knowing when fallback
// misbehaves, since on that pass the marker is the only tier that can succeed.
func TestIdentityRecordsItsSource(t *testing.T) {
	config := markerTestConfig()
	model := [2]string{"x-higress-llm-model", "my-org/qwen3-8b"}

	cases := []struct {
		name    string
		headers [][2]string
		want    identitySource
	}{
		{
			name:    "marker",
			headers: [][2]string{{"x-gpustack-auth-cache", vectorMarkerToken}, model},
			want:    sourceMarker,
		},
		{
			name:    "key table",
			headers: [][2]string{{"authorization", "Bearer gpustack_3192253c1f4a9b7e_" + vectorSecret}, model},
			want:    sourceKeys,
		},
		{
			name:    "unresolved",
			headers: [][2]string{{"authorization", "Bearer sk-not-ours"}, model},
			want:    sourceNone,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := resolveIdentity(config, tc.headers, vectorFallbackRoute, markerNow()).Source; got != tc.want {
				t.Errorf("source = %v, want %v", got, tc.want)
			}
		})
	}

	// Anonymity only arises on a public route.
	public := markerTestConfig()
	public.AccessPolicy = accessPolicyPublic
	if got := resolveIdentity(public, [][2]string{model}, vectorFallbackRoute, markerNow()).Source; got != sourceAnonymous {
		t.Errorf("source = %v, want %v", got, sourceAnonymous)
	}
}

// A marker that is present but unusable means a signing-key mismatch between
// the server and the gateway, or between two gateway pods. Falling through
// silently would hide it.
func TestRejectedMarkerIsReported(t *testing.T) {
	config := markerTestConfig()
	headers := func(marker string) [][2]string {
		return [][2]string{
			{"x-gpustack-auth-cache", marker},
			{"x-higress-llm-model", "my-org/qwen3-8b"},
			{"authorization", "Bearer gpustack_3192253c1f4a9b7e_" + vectorSecret},
		}
	}

	wrongKey, err := signMarker([]byte(strings.Repeat("0", 64)), vectorMarkerClaims, time.Unix(vectorMarkerExp, 0))
	if err != nil {
		t.Fatalf("signMarker: %v", err)
	}
	id := resolveIdentity(config, headers(wrongKey), vectorFallbackRoute, markerNow())
	if !id.MarkerRejected {
		t.Error("an unverifiable marker was not reported")
	}
	if id.Source != sourceKeys {
		t.Errorf("source = %v, want the tier-1 fallback", id.Source)
	}

	if resolveIdentity(config, headers(vectorMarkerToken), vectorFallbackRoute, markerNow()).MarkerRejected {
		t.Error("a valid marker was reported as rejected")
	}
	if resolveIdentity(config, [][2]string{
		{"x-higress-llm-model", "my-org/qwen3-8b"},
		{"authorization", "Bearer gpustack_3192253c1f4a9b7e_" + vectorSecret},
	}, vectorFallbackRoute, markerNow()).MarkerRejected {
		t.Error("an absent marker was reported as rejected")
	}
}

// Nothing strips a client-supplied copy of the marker header, and the marker
// travels on the *upstream* request -- so whoever receives those requests (a
// worker, an APM, a third-party provider) gets a fresh bearer for the caller
// with every one. What stops that from being a standing ability to act as them
// is that a marker is only honoured on a pass other than the one that minted
// it, which for a redirect means a different route name.
func TestMarkerIsRefusedOnTheRouteThatMintedIt(t *testing.T) {
	headers := [][2]string{
		{"x-gpustack-auth-cache", vectorMarkerToken},
		{"x-higress-llm-model", "my-org/qwen3-8b"},
	}

	replayed := resolveIdentity(markerTestConfig(), headers, vectorMarkerRoute, markerNow())
	if replayed.State == identityResolved {
		t.Error("a marker replayed on the route it names must not resolve an identity")
	}
	if !replayed.MarkerRejected {
		t.Error("the rejection should be visible, so the request falls back to its credential")
	}

	onFallback := resolveIdentity(markerTestConfig(), headers, vectorFallbackRoute, markerNow())
	if onFallback.State != identityResolved {
		t.Error("the pass the marker exists for must still resolve")
	}
}

// A marker minted before the route claim existed cannot be placed, so it is not
// honoured. Rejecting rather than trusting is the safe direction: the request
// falls back to its credential.
func TestMarkerWithoutARouteIsRefused(t *testing.T) {
	token, err := signMarker([]byte(vectorMarkerKey),
		markerClaims{ID: "ak:3192253c1f4a9b7e", Consumer: "c.gpustack-7", Model: "m"},
		time.Unix(vectorMarkerExp, 0))
	if err != nil {
		t.Fatalf("signMarker: %v", err)
	}

	id := resolveIdentity(markerTestConfig(), [][2]string{
		{"x-gpustack-auth-cache", token},
		{"x-higress-llm-model", "m"},
	}, vectorFallbackRoute, markerNow())

	if id.State == identityResolved {
		t.Error("a marker with no route claim must not resolve an identity")
	}
}

// Every allowing pass re-mints, the redirect pass included. Stamping that
// pass's own route would produce a marker naming the fallback route -- which
// differs from the main route and would then be accepted when replayed there,
// reopening what TestMarkerIsRefusedOnTheRouteThatMintedIt closes.
func TestReMintingKeepsTheRouteTheMarkerWasMintedOn(t *testing.T) {
	fromMarker := identity{
		State:     identityResolved,
		Source:    sourceMarker,
		AccessKey: "3192253c1f4a9b7e",
		Route:     vectorMarkerRoute,
	}

	claims, ok := markerClaimsFor(markerTestConfig(), fromMarker,
		"my-org/qwen3-8b", "3192253c1f4a9b7e.gpustack-7", vectorFallbackRoute)

	if !ok {
		t.Fatal("the redirect pass must still be able to mint")
	}
	if claims.Route != vectorMarkerRoute {
		t.Errorf("route = %q, want the route of the first mint (%q)", claims.Route, vectorMarkerRoute)
	}
}
